baseURL = 'https://space.tinkerberos.win/'
locale = 'en-us'
title = 'tinkerberos'
theme = "PaperMod"

# Completely disable tags and categories
disableKinds = ["taxonomy", "term"]

[taxonomies]
# Intentionally left empty to remove default tags/categories
